import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterController from "@/components/FooterController"; // client footer

export const metadata = {
  title: "Ecozon",
  description: "Generated by Next.js",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-1">{children}</main>
        <FooterController />
      </body>
    </html>
  );
}
